# Generated by Django 3.0.3 on 2020-02-16 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id_classe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_classe', models.CharField(choices=[('tc1', 'TC1'), ('tc2', 'TC2'), ('dic1', 'DIC1'), ('dic2', 'DIC2'), ('dic3', 'DIC3')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id_dept', models.AutoField(primary_key=True, serialize=False)),
                ('nom_dept', models.CharField(choices=[('TR', 'Tronc Commun'), ('GC', 'Génie Civil'), ('GEM', 'Génie Electromécanique'), ('FA', 'Filière Aréonautique'), ('GIT', 'Génie Informatique et Télécommunications')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_ens', models.CharField(max_length=200)),
                ('prof_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id_matiere', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=200)),
                ('id_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Prof')),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Classe')),
                ('eleve_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='id_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Departement'),
        ),
        migrations.CreateModel(
            name='Class_mat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_semestre', models.CharField(max_length=20)),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Classe')),
                ('id_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Matiere')),
            ],
        ),
    ]
