# Generated by Django 3.0.3 on 2020-03-03 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='document/pdfs')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='document/cover')),
                ('matiere_doc',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Matiere')),
            ],
        ),
    ]
