# Generated by Django 3.0.3 on 2020-03-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_document_type_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='cover',
        ),
        migrations.AddField(
            model_name='document',
            name='extension_doc',
            field=models.CharField(
                choices=[('ppt', 'ppt'), ('docx', 'docx'), ('pdf', 'pdf'), ('zip', 'zip'), ('xls', 'xls'),
                         ('autre', 'autre')], default='pdf', max_length=10),
        ),
    ]
