# Generated by Django 3.0.3 on 2020-03-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_auto_20200304_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='extension_doc',
            field=models.CharField(
                choices=[('ppt', 'ppt'), ('docx', 'docx'), ('pdf', 'pdf'), ('zip', 'zip'), ('xls', 'xls'),
                         ('autre', 'autre')], default='autre', max_length=10),
        ),
    ]
