INSERT INTO accounts_matiere(id_classe_id,libelle)
VALUES (22,'Anglais Technique  I'),
(22,'Travaux d’Atelier  I'),
(22,'Chimie Générale'),
(22,'Informatique I'),
(22,'Informatique  II'),
(22,'Calcul différentiel et Intégral  I'),
(22,'Algèbre Linéaire'),
(22,'Calcul différentiel et Intégral  II'),
(22,'Cinématique et Dynamique'),
(22,'Electromagnétisme'),
(22,'Dessin Technique I'),
(22,'Dessin Technique II'),
(22,'Géométrie Descriptive'),
(22,'Techniques d’expression'),
(22,'Thermodynamique générale'),
(23,'Travaux d’Atelier  II (Option GC et GEM)'),
(23,'Comptabilité générale'),
(23,'Transfert de Chaleur (Option GC et GEM)'),
(23,'Programmation Avancée (Option GC et GEM)'),
(23,'Introduction à l’économie'),
(23,'Adm. de l’Entreprise et Relations de travail'),
(23,'Analyse Vectorielle'),
(23,'Equations différentielles'),
(23,'Analyse Numérique'),
(23,'Probabilités et Statistiques'),
(23,'Compléments de Maths Appliquées'),
(23,'Mécanique Statique (Option GC et GEM)'),
(23,'Ondes et Vibrations (Option GC et GEM)'),
(23,'Dessin Technique III (DAO, CAO) (Option GC et GEM)'),
(23,'Droit'),
(23,'Science des Matériaux (Option GC et GEM)'),
(23,'Analyse de données (Option GIT'),
(23,'Architecture des Ordinateurs et Système d’Exploitation 1 (Option GIT)'),
(23,'Programmation Impérative 1 (Option GIT)'),
(23,'Développement Web 1 (Option GIT)');

